#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching RosAria..."
sudo chmod 777 /dev/ttyUSB0
rosrun rosaria RosAria &
pid="$pid $!"

sleep 5s

echo "Launching Laser Scan Assembler"
roslaunch pioneer_ros laser_scan_assembler &
pid="$pid $!"

sleep 1s

echo "Launching navigation stack..."
roslaunch nav_bundle nav_bundle.launch &
pid="$pid $!"

sleep 3s

echo "Launching controller..."
roslaunch pioneer_ros pioneer_controller.launch &
pid="$pid $!"

sleep 4s

echo "Launching Map"
rosrun moded_map_server moded_map_server AlmostPerfectMap.yaml &
pid="$pid $!"

sleep 3s

echo "Launching Rviz..."
roslaunch pioneer_description pioneer_rviz.launch &
pid="$pid $!"

#sleep 1s

#echo "Launching estop..."
#rqt --standalone rqt_estop

#sleep 1s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
