#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching RosAria..."
sudo chmod 777 /dev/ttyUSB0
rosrun rosaria RosAria &
pid="$pid $!"

sleep 5s

echo "Launching Rosaria transform"
rosrun rosaria transform &
pid="$pid $!"

sleep 1s

echo "Launching Urg Node"
sudo chmod 777 /dev/ttyACM0
rosrun urg_node urg_node &
pid="$pid $!"

sleep 3sv

echo "Launching Gmapping..."
rosrun gmapping slam_gmapping &
pid="$pid $!"

sleep 4s

echo "Launching Map"
rosrun moded_map_server moded_map_server elevadores.yaml &
pid="$pid $!"

sleep 3s

echo "Launching Rviz..."
roslaunch pioneer_description pioneer_rviz.launch &
pid="$pid $!"

#sleep 1s

#echo "Launching estop..."
#rqt --standalone rqt_estop

#sleep 1s

trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
