#!/bin/bash
 
my_pid=$$
echo "My process ID is $my_pid"

echo "Launching roscore..."
roscore &
pid=$!
sleep 5s

echo "Launching RosAria..."
sudo chmod 777 /dev/ttyUSB0
rosrun rosaria RosAria &
pid="$pid $!"

sleep 1s

echo "Launching transform Node"
rosrun rosaria transform &
pid="$pid $!"

sleep 1s

echo "Launching Urg Node"
sudo chmod 777 /dev/ttyACM0
rosrun urg_node urg_node &
pid="$pid $!"


sleep 1s

echo "Launching transform publishers..."
roslaunch pioneer_ros pioneer_ros.launch &
pid="$pid $!"

sleep 3s

echo "Launching navigation stack..."
roslaunch nav_bundle nav_bundle.launch &
pid="$pid $!"

sleep 3s

echo "Launching controller..."
roslaunch pioneer_ros pioneer_controller.launch &
pid="$pid $!"

sleep 4s

echo "Launching Map"
rosrun moded_map_server moded_map_server gazebo5FloorMap.yaml &
pid="$pid $!"

sleep 3s

echo "Launching Rviz..."
roslaunch pioneer_description pioneer_rviz.launch &
pid="$pid $!"


sleep 1s

echo "Launching Teleop"
rosrun teleop_keyobard_twist_keyboard_rosaria teleop_keyobard_twist_keyboard.py &
pid="$pid $!"


trap "echo Killing all processes.; kill -2 TERM $pid; exit" SIGINT SIGTERM

sleep 24h
